text[0] = "..."
text[1] = "what a shame...";
text[2] = "you couldn't even react";
text[3] = "...";
text[4] = "''Is he mad at me?''";
text[5] = "you were so foolish";
text[6] = "''He sent all those people with guns.''";
text[7] = "...";
text[8] = "*you remember her drawing*";
text[9] = "A knight with long hair, coming to the rescue";
text[10] = "...";
text[11] = "''I'll make sure no one ever hurts you again''";
text[12] = "...";
text[13] = "Oh...";
text[14] = "what is this?";
text[15] = "he is long gone now"
text[16] = "there is nothing you can do"
text[17] = "don't be a fool"
text[18] = "..."
text[19] = "''Goodbye Mr. Goodman! <3''"
text[20] = "AHAHAHAHAAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHAHHAHAHAHAH"
text[21] = "..."
text[22] = "No more Mr. Goodman -- I see...";
text[23] = "Do what you will";
text[24] = "you know where to find him";

